// Package garrison implements the committed tier: a loadout materialised into a
// repository as real files, recorded in a lockfile that is committed beside
// them.
//
// It is the deliberate opposite of internal/spawn. A spawn is personal - a
// symlink into one machine's store, kept out of git by .git/info/exclude, and
// governed by a lease with a lifetime. A garrison is shared - real file content
// that survives a clone, tracked by the committed lockfile, and governed by
// nothing else. There is no lease, so no reaper pass can ever end one.
//
// The lockfile is the source of truth for what should be on disk. It records
// every source with its resolved commit, and every file barracks wrote with the
// digest it wrote. That is what makes a checkout that no longer matches
// detectable (Check) instead of silently accepted, and what makes removal able
// to prove a file is barracks' own before deleting it (Remove).
package garrison

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/tobi404/barracks/internal/loadout"
	"github.com/tobi404/barracks/internal/source"
	"gopkg.in/yaml.v3"
)

// LockName is the committed manifest's filename, at the repository root.
//
// A lockfile rather than a config file: it is generated, it pins commits, and it
// is read to reproduce a tree - the same job Cargo.lock or package-lock.json
// does. The root is the only place that works, because one garrison can install
// into several agents' directories at once and a per-directory manifest would
// split one reviewable record across them.
const LockName = "barracks.lock"

// Version is the lockfile format version barracks writes.
const Version = 1

const lockHeader = `# barracks lockfile - generated by ` + "`barracks garrison`" + `. Commit it.
#
# It records exactly which sources, at which commits, produced the skill files
# in this repository. A teammate needs nothing but a clone to use them; with
# barracks installed they can run ` + "`barracks inspect`" + ` to check this tree still
# matches, and ` + "`barracks garrison`" + ` to put it back if it does not.
#
# Do not edit by hand: the digests below are how barracks proves a file is its
# own before it overwrites or removes one.
`

// File is one vendored file, recorded so removal and verification can prove
// barracks wrote it.
//
// Path is relative to the skill's Dir and always slash-separated, so a lockfile
// written on one operating system reads correctly on another.
type File struct {
	Path   string `yaml:"path"`
	Digest string `yaml:"digest"`
	// Exec records the executable bit, the only mode detail git itself tracks.
	Exec bool `yaml:"exec,omitempty"`
}

// Skill is one skill directory vendored into one agent's skills directory.
type Skill struct {
	Name string `yaml:"name"`
	// Target is the registry ID of the agent whose directory this landed in.
	Target string `yaml:"target"`
	// Dir is the skill directory, repo-root-relative and slash-separated.
	Dir string `yaml:"dir"`
	// Source is the ident of the equipped source it came from.
	Source string `yaml:"source"`
	Files  []File `yaml:"files"`
}

// Source is a frozen copy of one equipped source.
//
// The whole source is recorded, not just its ident, so that repairing a
// checkout needs the lockfile and nothing else - a teammate who never trained
// this loadout can still run `barracks garrison` and get the recorded commits.
type Source struct {
	source.Source `yaml:",inline"`
	Commit        string   `yaml:"commit"`
	Only          []string `yaml:"only,omitempty"`
	Except        []string `yaml:"except,omitempty"`
}

// Garrison is one loadout committed into this repository.
type Garrison struct {
	Loadout string `yaml:"loadout"`
	// Targets are the agent IDs this garrison installs into, in order.
	Targets   []string  `yaml:"targets"`
	UpdatedAt time.Time `yaml:"updated_at"`
	Sources   []Source  `yaml:"sources"`
	Skills    []Skill   `yaml:"skills"`
	// Dirs are directories barracks had to create, repo-relative and
	// slash-separated, shallowest first. Removal prunes them only while empty,
	// exactly as a lease does.
	Dirs []string `yaml:"dirs,omitempty"`
}

// Manifest is the whole lockfile.
type Manifest struct {
	Version   int        `yaml:"version"`
	Garrisons []Garrison `yaml:"garrisons"`
}

// Path is the lockfile's location for the repository rooted at root.
func Path(root string) string { return filepath.Join(root, LockName) }

// Load reads the lockfile. A repository with no lockfile yields an empty
// manifest and no error: not being garrisoned is a normal state, not a fault.
func Load(root string) (*Manifest, error) {
	b, err := os.ReadFile(Path(root))
	if err != nil {
		if os.IsNotExist(err) {
			return &Manifest{Version: Version}, nil
		}
		return nil, err
	}
	var m Manifest
	if err := yaml.Unmarshal(b, &m); err != nil {
		return nil, fmt.Errorf("parse %s: %w", LockName, err)
	}
	if m.Version > Version {
		return nil, fmt.Errorf("%s was written by a newer barracks (format version %d, this build understands %d); upgrade barracks", LockName, m.Version, Version)
	}
	return &m, nil
}

// Save writes the lockfile, or deletes it when nothing is garrisoned any more.
//
// Deleting rather than leaving an empty file behind matters: recalling the last
// garrison must show up in review as the lockfile going away, not as a husk
// nobody can tell is inert.
func (m *Manifest) Save(root string) error {
	path := Path(root)
	if len(m.Garrisons) == 0 {
		if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
			return err
		}
		return nil
	}
	m.Version = Version
	m.sort()
	b, err := yaml.Marshal(m)
	if err != nil {
		return err
	}
	return writeAtomic(path, append([]byte(lockHeader), b...), 0o644)
}

// sort orders the manifest so that re-running a garrison produces a stable
// file. An unstable generated file makes every pull request diff noise.
func (m *Manifest) sort() {
	sort.Slice(m.Garrisons, func(i, j int) bool { return m.Garrisons[i].Loadout < m.Garrisons[j].Loadout })
	for i := range m.Garrisons {
		g := &m.Garrisons[i]
		sort.Slice(g.Skills, func(a, b int) bool {
			if g.Skills[a].Dir == g.Skills[b].Dir {
				return g.Skills[a].Name < g.Skills[b].Name
			}
			return g.Skills[a].Dir < g.Skills[b].Dir
		})
		for j := range g.Skills {
			files := g.Skills[j].Files
			sort.Slice(files, func(a, b int) bool { return files[a].Path < files[b].Path })
		}
	}
}

// Find returns the garrison for a loadout, or nil.
func (m *Manifest) Find(name string) *Garrison {
	for i := range m.Garrisons {
		if m.Garrisons[i].Loadout == name {
			return &m.Garrisons[i]
		}
	}
	return nil
}

// Upsert replaces the garrison for g.Loadout, or appends it.
func (m *Manifest) Upsert(g Garrison) {
	for i := range m.Garrisons {
		if m.Garrisons[i].Loadout == g.Loadout {
			m.Garrisons[i] = g
			return
		}
	}
	m.Garrisons = append(m.Garrisons, g)
}

// Drop removes the garrison for a loadout, reporting whether there was one.
func (m *Manifest) Drop(name string) bool {
	for i := range m.Garrisons {
		if m.Garrisons[i].Loadout != name {
			continue
		}
		m.Garrisons = append(m.Garrisons[:i], m.Garrisons[i+1:]...)
		return true
	}
	return false
}

// SkillCount is how many skill directories this garrison holds.
func (g *Garrison) SkillCount() int { return len(g.Skills) }

// FileCount is how many files this garrison holds.
func (g *Garrison) FileCount() int {
	n := 0
	for _, s := range g.Skills {
		n += len(s.Files)
	}
	return n
}

// Claims reports whether the garrison records a file or skill directory at the
// repo-relative path rel, which is what stops a personal spawn landing on top
// of a committed one.
func (g *Garrison) Claims(rel string) bool {
	rel = strings.TrimSuffix(filepath.ToSlash(rel), "/")
	for _, s := range g.Skills {
		if s.Dir == rel || strings.HasPrefix(rel, s.Dir+"/") || strings.HasPrefix(s.Dir+"/", rel+"/") {
			return true
		}
	}
	return false
}

// Equipment renders the recorded sources back into loadout equipment, so a
// repair can run from the lockfile alone.
func (g *Garrison) Equipment() []loadout.Equipment {
	out := make([]loadout.Equipment, 0, len(g.Sources))
	for _, s := range g.Sources {
		out = append(out, loadout.Equipment{
			Source: s.Source,
			Commit: s.Commit,
			Only:   s.Only,
			Except: s.Except,
		})
	}
	return out
}

// Claims reports whether any garrison in the manifest records the repo-relative
// path rel, and names the loadout that does.
func (m *Manifest) Claims(rel string) (string, bool) {
	for i := range m.Garrisons {
		if m.Garrisons[i].Claims(rel) {
			return m.Garrisons[i].Loadout, true
		}
	}
	return "", false
}

func writeAtomic(path string, data []byte, mode os.FileMode) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	tmp, err := os.CreateTemp(filepath.Dir(path), ".barracks-tmp-*")
	if err != nil {
		return err
	}
	defer os.Remove(tmp.Name())
	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	if err := os.Chmod(tmp.Name(), mode); err != nil {
		return err
	}
	return os.Rename(tmp.Name(), path)
}
